/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./shared/components/Button/Button.vue')['default']
    CollapsiblePanel: typeof import('./shared/components/CollapsiblePanel/CollapsiblePanel.vue')['default']
    DevPanel: typeof import('./components/DevPanel/DevPanel.vue')['default']
    GameCanvas: typeof import('./components/GameCanvas/GameCanvas.vue')['default']
    GameHistory: typeof import('./components/Sidebar/GameHistory/GameHistory.vue')['default']
    GameOverModal: typeof import('./components/GameOverModal.vue')['default']
    InputField: typeof import('./shared/components/InputField/InputField.vue')['default']
    LazyImage: typeof import('./shared/components/LazyImage/LazyImage.vue')['default']
    Matches: typeof import('./components/Sidebar/Matches/Matches.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./shared/components/SelectField/SelectField.vue')['default']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    Spinner: typeof import('./shared/components/Spinner/Spinner.vue')['default']
    StartModal: typeof import('./components/StartModal.vue')['default']
    TilePreview: typeof import('./components/Sidebar/TilePreview/TilePreview.vue')['default']
    VolumeControl: typeof import('./components/Sidebar/VolumeControl/VolumeControl.vue')['default']
  }
}
